feat: update

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -1,4 +1,4 @@
-FROM ruby:%%RUBY_VERSION%%-buster
+FROM ruby:%%RUBY_VERSION%%
 
 MAINTAINER Sergey Homa srghma@gmail.com
 
@@ -10,9 +10,9 @@ RUN apt-get update -y; \
   apt-get install -y build-essential libpq-dev lsb-release
 
 ############ NODEJS ############
-# stolen from here https://github.com/nodejs/docker-node/blob/master/10/stretch/Dockerfile
+# stolen from here https://github.com/nodejs/docker-node/blob/main/20/bookworm/Dockerfile
 
-ENV NODE_VERSION 10.16.3
+ENV NODE_VERSION 20.12.2
 
 RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
   && case "${dpkgArch##*-}" in \
@@ -24,56 +24,113 @@ RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
     i386) ARCH='x86';; \
     *) echo "unsupported architecture"; exit 1 ;; \
   esac \
+  # use pre-existing gpg directory, see https://github.com/nodejs/docker-node/pull/1895#issuecomment-1550389150
+  && export GNUPGHOME="$(mktemp -d)" \
   # gpg keys listed at https://github.com/nodejs/node#release-keys
   && set -ex \
   && for key in \
-    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
-    FD3A5288F042B6850C66B31F09FE44734EB7990E \
-    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
-    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
-    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
-    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
-    77984A986EBC2AA786BC0F66B01FBB92821C587A \
-    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
     4ED778F539E3634C779C87C6D7062848A1AB005C \
-    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
-    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
+    141F07595B7B3FFE74309A937405533BE57C7D57 \
+    74F12602B6F1C4E913FAA37AD3A89613643B6201 \
+    DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7 \
+    61FC681DFB92A079F1685E77973F295594EC4689 \
+    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
+    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
+    890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4 \
+    C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
+    108F52B48DB57BB0CC439B2997B01419BD92F80A \
+    A363A499291CBBC940DD62E41F10027AF002F8B0 \
+    CC68F5A3106FF448322E48ED27F5E38D5B0A215F \
   ; do \
-    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
-    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
-    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
+      gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
+      gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
   done \
   && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
   && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
   && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
+  && gpgconf --kill all \
+  && rm -rf "$GNUPGHOME" \
   && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
   && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
   && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
-  && ln -s /usr/local/bin/node /usr/local/bin/nodejs
-
-ENV YARN_VERSION 1.17.3
-
-RUN set -ex \
-  && for key in \
-    6A010C5166006599AA17F08146C2130DFD2497F5 \
-  ; do \
-    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
-    gpg --batch --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
-    gpg --batch --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
-  done \
-  && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
-  && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc" \
-  && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
-  && mkdir -p /opt \
-  && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
-  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
-  && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
-  && rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz
+  && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
+  # smoke tests
+  && node --version \
+  && npm --version
 
 ############ NODEJS ############
 
 # ############ POSTGRES ############
-# stolen from https://github.com/docker-library/postgres/blob/master/13/Dockerfile
+# stolen from https://github.com/docker-library/postgres/blob/master/16/bookworm/Dockerfile
+
+# explicitly set user/group IDs
+RUN set -eux; \
+  groupadd -r postgres --gid=999; \
+# https://salsa.debian.org/postgresql/postgresql-common/blob/997d842ee744687d99a2b2d95c1083a2615c79e8/debian/postgresql-common.postinst#L32-35
+  useradd -r -g postgres --uid=999 --home-dir=/var/lib/postgresql --shell=/bin/bash postgres; \
+# also create the postgres user's home directory with appropriate permissions
+# see https://github.com/docker-library/postgres/issues/274
+  mkdir -p /var/lib/postgresql; \
+  chown -R postgres:postgres /var/lib/postgresql
+
+RUN set -ex; \
+  apt-get update; \
+  apt-get install -y --no-install-recommends \
+    gnupg \
+# https://www.postgresql.org/docs/16/app-psql.html#APP-PSQL-META-COMMAND-PSET-PAGER
+# https://github.com/postgres/postgres/blob/REL_16_1/src/include/fe_utils/print.h#L25
+# (if "less" is available, it gets used as the default pager for psql, and it only adds ~1.5MiB to our image size)
+    less \
+  ; \
+  rm -rf /var/lib/apt/lists/*
+
+# grab gosu for easy step-down from root
+# https://github.com/tianon/gosu/releases
+ENV GOSU_VERSION 1.17
+RUN set -eux; \
+  savedAptMark="$(apt-mark showmanual)"; \
+  apt-get update; \
+  apt-get install -y --no-install-recommends ca-certificates wget; \
+  rm -rf /var/lib/apt/lists/*; \
+  dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+  wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+  wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+  export GNUPGHOME="$(mktemp -d)"; \
+  gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+  gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+  gpgconf --kill all; \
+  rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+  apt-mark auto '.*' > /dev/null; \
+  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
+  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+  chmod +x /usr/local/bin/gosu; \
+  gosu --version; \
+  gosu nobody true
+
+# make the "en_US.UTF-8" locale so postgres will be utf-8 enabled by default
+RUN set -eux; \
+  if [ -f /etc/dpkg/dpkg.cfg.d/docker ]; then \
+# if this file exists, we're likely in "debian:xxx-slim", and locales are thus being excluded so we need to remove that exclusion (since we need locales)
+    grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker; \
+    sed -ri '/\/usr\/share\/locale/d' /etc/dpkg/dpkg.cfg.d/docker; \
+    ! grep -q '/usr/share/locale' /etc/dpkg/dpkg.cfg.d/docker; \
+  fi; \
+  apt-get update; apt-get install -y --no-install-recommends locales; rm -rf /var/lib/apt/lists/*; \
+  echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen; \
+  locale-gen; \
+  locale -a | grep 'en_US.utf8'
+ENV LANG en_US.utf8
+
+RUN set -eux; \
+  apt-get update; \
+  apt-get install -y --no-install-recommends \
+    libnss-wrapper \
+    xz-utils \
+    zstd \
+  ; \
+  rm -rf /var/lib/apt/lists/*
+
+RUN mkdir /docker-entrypoint-initdb.d
 
 RUN set -ex; \
 # pub   4096R/ACCC4CF8 2011-10-13 [expires: 2019-07-02]
@@ -81,14 +138,16 @@ RUN set -ex; \
 # uid                  PostgreSQL Debian Repository
   key='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8'; \
   export GNUPGHOME="$(mktemp -d)"; \
-  gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-  gpg --batch --export "$key" > /etc/apt/trusted.gpg.d/postgres.gpg; \
-  command -v gpgconf > /dev/null && gpgconf --kill all; \
-  rm -rf "$GNUPGHOME"; \
-  apt-key list
+  mkdir -p /usr/local/share/keyrings/; \
+  gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
+  gpg --batch --export --armor "$key" > /usr/local/share/keyrings/postgres.gpg.asc; \
+  gpgconf --kill all; \
+  rm -rf "$GNUPGHOME"
 
-ENV PG_MAJOR 13
-ENV PG_VERSION 13.2-1.pgdg100+1
+ENV PG_MAJOR 16
+ENV PATH $PATH:/usr/lib/postgresql/$PG_MAJOR/bin
+
+ENV PG_VERSION 16.2-1.pgdg120+2
 
 RUN set -ex; \
   \
@@ -96,44 +155,48 @@ RUN set -ex; \
   export PYTHONDONTWRITEBYTECODE=1; \
   \
   dpkgArch="$(dpkg --print-architecture)"; \
+  aptRepo="[ signed-by=/usr/local/share/keyrings/postgres.gpg.asc ] http://apt.postgresql.org/pub/repos/apt/ bookworm-pgdg main $PG_MAJOR"; \
   case "$dpkgArch" in \
-    amd64 | arm64 | i386 | ppc64el) \
+    amd64 | arm64 | ppc64el | s390x) \
 # arches officialy built by upstream
-      echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main $PG_MAJOR" > /etc/apt/sources.list.d/pgdg.list; \
+      echo "deb $aptRepo" > /etc/apt/sources.list.d/pgdg.list; \
       apt-get update; \
       ;; \
     *) \
 # we're on an architecture upstream doesn't officially build for
 # let's build binaries from their published source packages
-      echo "deb-src http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main $PG_MAJOR" > /etc/apt/sources.list.d/pgdg.list; \
+      echo "deb-src $aptRepo" > /etc/apt/sources.list.d/pgdg.list; \
       \
-      case "$PG_MAJOR" in \
-        9.* | 10 ) ;; \
-        *) \
-# https://github.com/docker-library/postgres/issues/484 (clang-6.0 required, only available in stretch-backports)
-# TODO remove this once we hit buster+
-          echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list.d/pgdg.list; \
-          ;; \
-      esac; \
+      savedAptMark="$(apt-mark showmanual)"; \
       \
       tempDir="$(mktemp -d)"; \
       cd "$tempDir"; \
       \
-      savedAptMark="$(apt-mark showmanual)"; \
+# create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+      apt-get update; \
+      apt-get install -y --no-install-recommends dpkg-dev; \
+      echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list; \
+      _update_repo() { \
+        dpkg-scanpackages . > Packages; \
+# work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+#   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+#   ...
+#   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+        apt-get -o Acquire::GzipIndexes=false update; \
+      }; \
+      _update_repo; \
       \
 # build .deb files from upstream's source packages (which are verified by apt-get)
-      apt-get update; \
-# we need DEBIAN_FRONTEND on postgresql-13 for slapd ("Please enter the password for the admin entry in your LDAP directory."); see https://bugs.debian.org/929417
-      DEBIAN_FRONTEND=noninteractive \
-      apt-get build-dep -y \
-        postgresql-common pgdg-keyring \
-        "postgresql-$PG_MAJOR=$PG_VERSION" \
-      ; \
-      DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
-        apt-get source --compile \
-          postgresql-common pgdg-keyring \
-          "postgresql-$PG_MAJOR=$PG_VERSION" \
-      ; \
+      nproc="$(nproc)"; \
+      export DEB_BUILD_OPTIONS="nocheck parallel=$nproc"; \
+# we have to build postgresql-common first because postgresql-$PG_MAJOR shares "debian/rules" logic with it: https://salsa.debian.org/postgresql/postgresql/-/commit/99f44476e258cae6bf9e919219fa2c5414fa2876
+# (and it "Depends: pgdg-keyring")
+      apt-get build-dep -y postgresql-common pgdg-keyring; \
+      apt-get source --compile postgresql-common pgdg-keyring; \
+      _update_repo; \
+      apt-get build-dep -y "postgresql-$PG_MAJOR=$PG_VERSION"; \
+      apt-get source --compile "postgresql-$PG_MAJOR=$PG_VERSION"; \
+      \
 # we don't remove APT lists here because they get re-downloaded and removed later
       \
 # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
@@ -141,16 +204,10 @@ RUN set -ex; \
       apt-mark showmanual | xargs apt-mark auto > /dev/null; \
       apt-mark manual $savedAptMark; \
       \
-# create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
       ls -lAFh; \
-      dpkg-scanpackages . > Packages; \
+      _update_repo; \
       grep '^Package: ' Packages; \
-      echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list; \
-# work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
-#   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
-#   ...
-#   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
-      apt-get -o Acquire::GzipIndexes=false update; \
+      cd /; \
       ;; \
   esac; \
   \
@@ -169,6 +226,16 @@ RUN set -ex; \
   fi; \
   \
 # some of the steps above generate a lot of "*.pyc" files (and setting "PYTHONDONTWRITEBYTECODE" beforehand doesn't propagate properly for some reason), so we clean them up manually (as long as they aren't owned by a package)
-  find /usr -name '*.pyc' -type f -exec bash -c 'for pyc; do dpkg -S "$pyc" &> /dev/null || rm -vf "$pyc"; done' -- '{}' +
+  find /usr -name '*.pyc' -type f -exec bash -c 'for pyc; do dpkg -S "$pyc" &> /dev/null || rm -vf "$pyc"; done' -- '{}' +; \
+  \
+  postgres --version
+
+# make the sample config easier to munge (and "correct by default")
+RUN set -eux; \
+  dpkg-divert --add --rename --divert "/usr/share/postgresql/postgresql.conf.sample.dpkg" "/usr/share/postgresql/$PG_MAJOR/postgresql.conf.sample"; \
+  cp -v /usr/share/postgresql/postgresql.conf.sample.dpkg /usr/share/postgresql/postgresql.conf.sample; \
+  ln -sv ../postgresql.conf.sample "/usr/share/postgresql/$PG_MAJOR/"; \
+  sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" /usr/share/postgresql/postgresql.conf.sample; \
+  grep -F "listen_addresses = '*'" /usr/share/postgresql/postgresql.conf.sample
 
 # ############ POSTGRES ############
